_target_: src_medical.models.pokeman_module.PokemanLitModule

optimizer:
#  _target_: torch.optim.Adam
  _target_: src_medical.optim.Myadam.AdamEntropy
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
net:
  _target_: src_medical.models.components.resnet18.Backbone
#  _target_: src_medical.models.components.simple_dense_net.SimpleDenseNet
#  input_size: 784
#  lin1_size: 64
#  lin2_size: 128
#  lin3_size: 64
#  output_size: 5
